-- 코드를 작성해주세요
SELECT b.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM ITEM_INFO AS a
JOIN ITEM_TREE AS b
ON a.ITEM_ID = b.ITEM_ID
WHERE b.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY b.ITEM_ID DESC